### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by anouar1991** [lethaiq/MALCOM#1]
Hello,
I am working on adversarial NLP models attacks. I would like to include your method in my study. Could you please inform me when will the code be available?
Thank you in advance.
Best regards

**Comment by lethaiq** [comment]
@anouar1991 

I will try to clean the code and publish it.
I am sorry for the delay.

**Comment by anouar1991** [comment]
> @anouar1991
> 
> I will try to clean the code and publish it.
> I am sorry for the delay.

Thank you very much.

**Comment by anouar1991** [comment]
Hello, 
Is it possible to reopen the issue and close it when it's resolved?
Regards
